import os

API_BASE_URL = "http://localhost:8000"
STORAGE_ACCOUNT_NAME = "magnetometerdatastr"
PROJECTS_CONTAINER = "mag-projects"
DATASETS_CONTAINER = "mag-datasets"
SURVEY_DATA_SELECTED = "survey_dataset_selected_id"
OBS_DATA_SELECTED = "obs_dataset_selected_id"
SURVEY_DATA_START_IDX = "SURVEY_DATA_START_IDX"
WORKING_DATASET = "WORKING_DATASET"
DIURNAL_COMPUTED = "DIURNAL_COMPUTED"
SURVEY_DATA_END_IDX = "SURVEY_DATA_START_IDX"
POINTS_TO_CLIP = "POINTS_TO_CLIP"
DISABLED_TABS = False
PROJECT_ROOT = os.getcwd()
NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE"
ANNOTATION = "ANNOTATION"
