class Consts:
    NOTIFS_MESSAGE = "NOTIFS_MESSAGE_KEY"
    LOADING_DISPLAY_STATE = "LOADING"
    PROCESSING_DISPLAY_STATE = "PROCESSING"
    SAVING_DISPLAY_STATE = "SAVING"
    FINISHED_DISPLAY_STATE = "FINISHED"
    APP_NAME = "ucc-mag-processor"